apiVersion: apps/v1
kind: Deployment
metadata:
  name: chatbot-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chatbot-frontend
  template:
    metadata:
      labels:
        app: chatbot-frontend
    spec:
      containers:
      - name: chatbot-frontend
        image: logesh2001/chatbot-frontend:latest
        ports:
        - containerPort: 8501
---
apiVersion: v1
kind: Service
metadata:
  name: chatbot-frontend
spec:
  selector:
    app: chatbot-frontend
  ports:
  - port: 8501
    targetPort: 8501
  type: NodePort
