apiVersion: apps/v1
kind: Deployment
metadata:
  name: rag-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rag-api
  template:
    metadata:
      labels:
        app: rag-api
    spec:
      containers:
      - name: rag-api
        image: logesh2001/rag-api:latest
        ports:
        - containerPort: 8000
        env:
        - name: POSTGRES_DB
          value: "yourdbname"
        - name: POSTGRES_USER
          value: "youruser"
        - name: POSTGRES_PASSWORD
          value: "yourpassword"
        - name: PINECONE_ENVIRONMENT
          value: "us-east-1-aws"
        - name: PINECONE_INDEX
          value: "trace-chatbot-index"
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: "/secrets/gcp.json"
        - name: OPENAI_API_KEY
          valueFrom:
            secretKeyRef:
              name: api-secrets
              key: OPENAI_API_KEY
        - name: PINECONE_API_KEY
          valueFrom:
            secretKeyRef:
              name: api-secrets
              key: PINECONE_API_KEY
        volumeMounts:
        - name: gcp-creds
          mountPath: /secrets
          readOnly: true
      volumes:
      - name: gcp-creds
        configMap:
          name: gcp-config
---
apiVersion: v1
kind: Service
metadata:
  name: rag-api
spec:
  selector:
    app: rag-api
  ports:
  - port: 8000
    targetPort: 8000
  type: ClusterIP
